django_app/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # post앱의 index뷰를 root url에 연결시킨다.
    # url(r'^$', post_views.index),

    # 새 view를 만들어 redirect시키는 방법
    url(r'^$', views.index, name='index'),

    # Class-based View중 RedirectView를 사용하는 방법
    # url(r'^$', RedirectView.as_view(pattern_name='post:post_list')),

    # post앱의 urls.py모듈을 include시킨다
    url(r'^post/', include('post.urls')),
    url(r'^member/', include('member.urls')),
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

django_app/post/urls.py
from django.conf.urls import url
from . import views

# URL Namespace
# https://docs.djangoproject.com/en/1.11/topics/http/urls/#url-namespaces
app_name = 'post'
urlpatterns = [
    # url() 사용법
    # https://docs.djangoproject.com/en/1.11/ref/urls/#url

    # post_list와 매칭
    # /post/$
    url(r'^$', views.post_list, name='post_list'),

    # post_detail과 매칭
    # /post/3/$, /post/35/$
    # 정규표현식에서 매칭된 그룹을 위치인수로 반환하는 방법
    # url(r'^(\d+)/$', views.post_detail),

    # 정규표현식에서 매칭된 그룹을 키워드인수로 반환하는 방법
    # 그룹의 가장 앞 부분에 ?P<패턴이름>을 지정
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),

    # post_create와 매칭
    url(r'^create/$', views.post_create, name='post_create'),

    # post_modify와 매칭
    url(r'^(?P<post_pk>\d+)/modify/$', views.post_modify, name='post_modify'),

    # post_delete와 매칭
    url(r'^(?P<post_pk>\d+)/delete/$', views.post_delete, name='post_delete'),

    # post_like와 매칭
    url(r'^(?P<post_pk>\d+)/like-toggle/$', views.post_like_toggle, name='post_like_toggle'),

    # comment_create와 매칭
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),

    # comment_modify와 매칭
    url(r'^comment/(?P<comment_pk>\d+)/modify/$', views.comment_modify, name='comment_modify'),

    # comment_delete와 매칭
    url(r'^comment/(?P<comment_pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),

    # hashtag_post_list와 매칭
    url(r'^tag/(?P<tag_name>\w+)/$', views.hashtag_post_list, name='hashtag_post_list'),

    # 위쪽의 결과들과 매칭되지 않을 경우
    # url(r'^.*/$', views.post_anyway, name='post_anyway'),
    url(r'^youtube/search/$', views.youtube_search, name='youtube_search'),
    url(r'^youtube/post/create/$', views.post_create_with_video, name='youtube_post_create'),
]

django_app/post/models/comment.py
import re

from django.conf import settings
from django.db import models
from django.urls import reverse

from .others import Tag
from .post import Post

__all__ = (
    'Comment',
    'CommentLike',
)


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()
    html_content = models.TextField(blank=True)
    tags = models.ManyToManyField('Tag')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='CommentLike',
        related_name='like_comments',
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.make_html_content_and_add_tags()

    def make_html_content_and_add_tags(self):
        # 해시태그에 해당하는 정규표현식
        p = re.compile(r'(#\w+)')
        # findall메서드로 해시태그 문자열들을 가져옴
        tag_name_list = re.findall(p, self.content)
        # 기존 content(Comment내용)을 변수에 할당
        ori_content = self.content
        # 문자열들을 순회하며
        for tag_name in tag_name_list:
            # Tag객체를 가져오거나 생성, 생성여부는 쓰지않는 변수이므로 _처리
            tag, _ = Tag.objects.get_or_create(name=tag_name.replace('#', ''))
            # 기존 content의 내용을 변경
            change_tag = '<a href="{url}" class="hash-tag">{tag_name}</a>'.format(
                # url=reverse('post:hashtag_post_list', args=[tag_name.replace('#', '')]),
                url=reverse('post:hashtag_post_list', kwargs={'tag_name': tag_name.replace('#', '')}),
                tag_name=tag_name
            )
            ori_content = re.sub(r'{}(?![<\w])'.format(tag_name), change_tag, ori_content, count=1)
            # content에 포함된 Tag목록을 자신의 tags필드에 추가
            if not self.tags.filter(pk=tag.pk).exists():
                self.tags.add(tag)
        # 편집이 완료된 문자열을 html_content에 저장
        self.html_content = ori_content
        super().save(update_fields=['html_content'])


class CommentLike(models.Model):
    comment = models.ForeignKey(Comment)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_date = models.DateTimeField(auto_now_add=True)

django_app/post/models/others.py
from django.db import models

__all__ = (
    'Tag',
)


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return 'Tag({})'.format(self.name)

django_app/post/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template import loader
from django.urls import reverse

from post.decorators import post_owner
from .forms import PostForm
from .models import Post

# 자동으로 Django에서 인증에 사용하는 User모델클래스를 리턴
#   https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#django.contrib.auth.get_user_model
User = get_user_model()


def post_list(request):
    # 모든 Post목록을 'posts'라는 key로 context에 담아 return render처리
    # post/post_list.html을 template으로 사용하도록 한다

    # 각 포스트에 대해 최대 4개까지의 댓글을 보여주도록 템플릿에 설정
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'post/post_list.html', context)


def post_detail(request, post_pk):
    # Model(DB)에서 post_pk에 해당하는 Post객체를 가져와 변수에 할당
    # ModelManager의 get메서드를 사용해서 단 한개의 객체만 가져온다
    # https://docs.djangoproject.com/en/1.11/ref/models/querysets/#get

    # 가져오는 과정에서 예외처리를 한다 (Model.DoesNotExist)
    try:
        post = Post.objects.get(pk=post_pk)
    except Post.DoesNotExist as e:
        # 1. 404 Notfound를 띄워준다
        # return HttpResponseNotFound('Post not found, detail: {}'.format(e))

        # 2. post_list view로 돌아간다
        # 2-1. redirect를 사용
        #   https://docs.djangoproject.com/en/1.11/topics/http/shortcuts/#redirect
        # return redirect('post:post_list')
        # 2-2. HttpResponseRedirect
        #   https://docs.djangoproject.com/en/1.11/ref/request-response/#django.http.HttpResponseRedirect
        url = reverse('post:post_list')
        return HttpResponseRedirect(url)

    # request에 대해 response를 돌려줄때는 HttpResponse나 render를 사용가능
    # template을 사용하려면 render함수를 사용한다
    # render함수는
    #   django.template.loader.get_template함수와
    #   django.http.HttpResponse함수를 축약해 놓은 shortcut이다
    #       https://docs.djangoproject.com/en/1.11/topics/http/shortcuts/#render

    # ! 이 뷰에서는 render를 사용하지 않고, 전체 과정(loader, HttpResponse)을 기술
    # Django가 템플릿을 검색할 수 있는 모든 디렉토리를 순회하며
    # 인자로 주어진 문자열값과 일치하는 템플릿이 있는지 확인 후,
    # 결과를 리턴 (django.template.backends.django.Template클래스형 객체)
    # get_template()메서드
    #   https://docs.djangoproject.com/en/1.11/topics/templates/#django.template.loader.get_template
    template = loader.get_template('post/post_detail.html')
    # dict형 변수 context의 'post'키에 post(Post객체)를 할당
    context = {
        # context로 전달될 dict의 "키"값이 템플릿에서 사용가능한 변수명이 됨
        'post': post,
    }
    # template에 인자로 주어진 context, request를 render함수를 사용해서 해당 template을 string으로 변환
    rendered_string = template.render(context=context, request=request)
    # 변환된 string을 HttpResponse형태로 돌려준다
    return HttpResponse(rendered_string)


@login_required
def post_create(request):
    # POST요청을 받아 Post객체를 생성 후 post_list페이지로 redirect
    if request.method == 'POST':
        ### PostForm을 쓰지 않은경우
        # # get_user_model을 이용해서 얻은 User클래스(Django에서 인증에 사용하는 유저모델)에서 임의의 유저 한명을 가져온다.
        # user = User.objects.first()
        # # 새 Post객체를 생성하고 DB에 저장
        # post = Post.objects.create(
        #     author=user,
        #     # request.FILES에서 파일 가져오기
        #     #   https://docs.djangoproject.com/en/1.11/topics/http/file-uploads/#basic-file-uploads
        #     # 가져온 파일을 ImageField에 넣도록 설정
        #     # 'file'은 POST요청시 input[type="file"]이 가진 name속성
        #     photo=request.FILES['photo'],
        # )
        # # POST요청시 name이 'comment'인 input에서 전달된 값을 가져옴
        # # dict.get()
        # #   https://www.tutorialspoint.com/python/dictionary_get.htm
        # comment_string = request.POST.get('comment', '')
        # # 빈 문자열 ''이나 None모두 False로 평가되므로
        # # if not으로 댓글로 쓸 내용 또는 comment키가 전달되지 않았음을 검사 가능
        # if comment_string:
        #     # 댓글로 사용할 문자열이 전달된 경우 위에서 생성한 post객체에 연결되는 Comment객체를 생성해준다
        #     post.comment_set.create(
        #         # 임의의 user를 사용하므로 나중에 실제 로그인된 사용자로 바꾸어주어야 함
        #         author=user,
        #         content=comment_string,
        #     )
        #     # 역참조로 가져온 RelatedManager를 사용하지 않을경우엔 아래와 같이 작업함
        #     # Comment.objects.create(
        #     #     post=post,
        #     #     author=user,
        #     #     content=comment_string,
        #     # )
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            # ModelForm의 save()메서드를 사용해서 Post객체를 가져옴
            post = form.save(author=request.user)
            return redirect('post:post_detail', post_pk=post.pk)
    else:
        # post/post_create.html을 render해서 리턴
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'post/post_create.html', context)


@post_owner
@login_required
def post_modify(request, post_pk):
    # 수정
    post = Post.objects.get(pk=post_pk)

    if request.method == 'POST':
        form = PostForm(data=request.POST, files=request.FILES, instance=post)
        form.save()
        return redirect('post:post_detail', post_pk=post_pk)
    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
    }
    return render(request, 'post/post_modify.html', context)

def post_delete(request, post_pk):
    # post_pk에 해당하는 Post에 대한 delete요청만을 받음
    # 처리완료후에는 post_list페이지로 redirect
    pass


def comment_create(request, post_pk):
    # POST요청을 받아 Comment객체를 생성 후 post_detail페이지로 redirect
    pass


def comment_modify(request, post_pk):
    # 수정
    pass


def comment_delete(request, post_pk, comment_pk):
    # POST요청을 받아 Comment객체를 delete, 이후 post_detail페이지로 redirect
    pass


def post_anyway(request):
    return redirect('post:post_list')

django_app/post/views/comment.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from post.decorators import comment_owner
from ..forms import CommentForm
from ..models import Post, Comment

__all__ = (
    'comment_create',
    'comment_modify',
    'comment_delete',
)


@require_POST
@login_required
def comment_create(request, post_pk):
    # URL에 전달되어온 post_pk로 특정 Post객체 가져옴
    post = get_object_or_404(Post, pk=post_pk)
    # URL의 GET parameter의 'next'값을 가져옴
    next = request.GET.get('next')
    # CommentForm data binding
    form = CommentForm(request.POST)

    # form이 유효할 경우, Comment생성
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    # form이 유효하지 않을 경우, 현재 request에 error메시지 추가
    else:
        result = '<br>'.join(['<br>'.join(v) for v in form.errors.values()])
        messages.error(request, result)
    # next값이 존재하면 해당 주소로, 없으면 post_detail로 이동
    if next:
        return redirect(next)
    return redirect('post:post_detail', post_pk=post.pk)


@comment_owner
@login_required
def comment_modify(request, comment_pk):
    # get_object_or_404를 이용해서 Comment객체 가져오기
    comment = get_object_or_404(Comment, pk=comment_pk)
    next = request.GET.get('next')
    if request.method == 'POST':
        # Form을 이용해 객체를 update시킴 (data에 포함된 부분만 update됨)
        form = CommentForm(data=request.POST, instance=comment)
        form.save()
        if next:
            return redirect(next)
        return redirect('post:post_detail', post_pk=comment.post.pk)
    else:
        # CommentForm에 기존 comment인스턴스의 내용을 채운 bound form
        form = CommentForm(instance=comment)
    context = {
        'form': form,
    }
    return render(request, 'post/comment_modify.html', context)


@comment_owner
@require_POST
@login_required
def comment_delete(request, comment_pk):
    # comment_delete이후에 원래 페이지로 돌아갈 수 있도록 처리해보기
    #   (리스트에서 삭제하면 해당 리스트의 post위치로)
    comment = get_object_or_404(Comment, pk=comment_pk)
    post = comment.post
    comment.delete()
    return redirect('post:post_detail', post_pk=post.pk)

django_app/post/views/youtube.py
import requests
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from post.models import Video, Post, Comment
from utils import youtube

__all__ = (
    'youtube_search',
    'post_create_with_video',
)


def youtube_search_original(request):
    # [1] 검색결과를 DB에 저장하고, 해당내용을 템플릿에서 보여주기!
    # 1. 유튜브 영상을 저장할 class Video(models.Model)생성
    # 2. 검색결과의 videoId를 Video의 youtube_id필드에 저장
    #       해당필드는 unique해야 함
    # 3. 검색결과에서 videoId가 Video의 youtube_id와 일치하는 영상이 이미 있을경우에는 pass,
    #    없을경우 새 Video객체를 만들어 DB에 저장
    # 4. 이후 검색결과가 아닌 자체 DB에서 QuerySet을 만들어 필터링한 결과를 템플릿에서 표시
    # !! - 빈칸으로 구분되면 and검색

    # [2] 위 과제로 완성된 검색결과에서 '포스팅하기'버튼을 구현, Post가 YouTube영상을 포함하도록 함
    #    검색결과에서 '포스팅하기'버튼을 누르면, 해당 Video와 연결된 Post를 생성
    #    post_list에서 Video와 연결된 Post는 영상을 보여주도록 함
    #    my_comment를 타이틀로 등록
    url_api_search = 'https://www.googleapis.com/youtube/v3/search'
    q = request.GET.get('q')
    if q:
        search_params = {
            'part': 'snippet',
            'key': 'AIzaSyACCLlnn_hlOpNk5XUBpRqs-iZWpbTm-J4',
            'maxResults': '10',
            'type': 'video',
            'q': q,
        }
        # YouTube의 search api에 요청, 응답 받음
        response = requests.get(url_api_search, params=search_params)
        # 응답은 JSON형태로 오며, json()메서드로 파이썬 객체 형식으로 변환
        data = response.json()
        # data내부의 'items'키에는 list형태의 데이터가 옴. 이를 순회
        for item in data['items']:
            # CustomManager를 사용해 object생성
            Video.objects.create_from_search_result(item)

        # 현재 검색어로 자체 DB의 내용들을 filter해서 전달
        # 제목내에 검색어가 포함되는지 여부
        # videos = Video.objects.filter(title__contains=q)
        # 제목과 설명(description)에 포함되는지
        # videos = Video.objects.filter(Q(title__contains=q) | Q(description__contains=q))
        # 검색어가 빈칸단위로 구분되어있을때 빈칸으로 split한 값들을 각각 포함하고 있는지 and연산
        # 원초적인 방법
        # FastCampus Web Programming School
        # Program Web Fast
        # videos = Video.objects.all()
        # for cur_q in q.split(' '):
        #     videos.filter(title__contains=cur_q)

        # regex사용법
        # and연산
        re_pattern = ''.join(['(?=.*{})'.format(item) for item in q.split()])
        # or연산
        # re_pattern = '|'.join(['({})'.format(item) for item in q.split()])
        # title과 description중 하나만 조건을 만족하면 됨
        videos = Video.objects.filter(
            Q(title__iregex=r'{}'.format(re_pattern)) |
            Q(description__iregex=r'{}'.format(re_pattern))
        )

        context = {
            'videos': videos,
            're_pattern': re_pattern,
            'query': videos.query,
        }
        # ex) 자체 DB쿼리
        # videos = Video.objects.filter(Q(title__contains=q) | Q(description__contains=q))
        # context = {
        #     'videos': videos,
        # }
    else:
        # 1. search list의 주소로 GET요청을 보냄
        #   주소: https://www.googleapis.com/youtube/v3/search
        #   params: part, key, q, maxResults, type
        # 2. 요청 결과를 response변수에 할당
        # 3. result = response.json()
        # 4. result를 템플릿에서 보여주기
        # search list API를 이용해서 (type: video, maxResults: 10)
        # request.GET.get('q')에 데이터가 있을 경우
        # requests.get을 사용한 결과를 변수에 할당하고
        # 해당 변수를 템플릿에서 표시
        context = {}
    return render(request, 'post/youtube_search.html', context)


def youtube_search(request):
    """
    유튜브 검색을 라이브러리 형태로 정리
    """
    context = dict()
    q = request.GET.get('q')
    if q:
        # YouTube검색부분을 패키지화
        data = youtube.search(q)
        for item in data['items']:
            Video.objects.create_from_search_result(item)
        re_pattern = ''.join(['(?=.*{})'.format(item) for item in q.split()])
        videos = Video.objects.filter(
            Q(title__regex=re_pattern) |
            Q(description__regex=re_pattern)
        )
        context['videos'] = videos
    return render(request, 'post/youtube_search.html', context)


@require_POST
@login_required
def post_create_with_video(request):
    # POST요청에서 video_pk값을 받음
    video_pk = request.POST['video_pk']
    # 받은 video_pk에 해당하는 Video인스턴스
    video = get_object_or_404(Video, pk=video_pk)

    # 해당 video를 갖는 Post생성
    post = Post.objects.create(
        author=request.user,
        video=video,
    )
    # 생성한 Post객체의 my_comment에 해당하는 Comment생성
    post.my_comment = Comment.objects.create(
        post=post,
        author=request.user,
        content=video.title
    )
    return redirect('post:post_detail', post_pk=post.pk)

django_app/templates/include/field_set.html
<!--
	form 자체에 대한 error
	(Form의 clean()메서드에서 발생한 ValidationError)
-->
{% if form.non_field_errors %}
<ul class="errors">
	{% for error in form.non_field_errors %}
	<li>{{ error }}</li>
	{% endfor %}
</ul>
{% endif %}

<!--form을 순회하면 form이 가진 각 필드를 매 루프마다 제공-->
{% for field in form %}
<div class="field-wrapper">
	<!--label태그(for에 field의 id를 가짐) 생성-->
	{{ field.label_tag }}
	<!--input을 생성-->
	{{ field }}

	<!--field에 help_text가 있을 경우-->
	{% if field.help_text %}
	<p class="help">{{ field.help_text }}</p>
	{% endif %}

	<!--field에 error가 있을 경우-->
	{% if field.errors %}
	<ul class="errors">
		{% for error in field.errors %}
		<li>{{ error }}</li>
		{% endfor %}
	</ul>
	{% endif %}
</div>
{% endfor %}

django_app/templates/include/post.html
{% load static %}
{% load custom_tags %}
<article id="post-{{ post.pk }}" class="post">
  <header>
    <div class="post-header-left">
      <img src="" alt="">
      <span class="header-author">{{ post.author }}</span>
    </div>
    <div class="post-header-right">

    </div>
  </header>
  <div class="post-photo-container">
    <!--
    url태그를 사용해서 post:post_detail view로 이동하는 URL을 reverse
    이때 post_pk라는 kwargs를 받으므로 post_pk key에 현재 post변수의 pk속성을 할당
    -->


    {% if type == 'list' %}
    <a href="{% url 'post:post_detail' post_pk=post.pk %}">
    {% endif %}

      {% if post.video %}
      <iframe width="100%" height="400" src="https://www.youtube.com/embed/{{ post.video.youtube_id }}" frameborder="0" allowfullscreen></iframe>
      {% else %}
      <img src="{{ post.photo.url }}" alt="">
      {% endif %}

    {% if type == 'list' %}
    </a>
    {% endif %}

  </div>
  <div class="post-bottom">
    <div class="post-btn-container clearfix">
      <div class="btn-left">
        <a href="#">
          <!--
            post:post_like_toggle로 요청하는 form구현
          -->
          <form action="{% url 'post:post_like_toggle' post_pk=post.pk %}" method="POST" class="form-inline">
            {% csrf_token %}
            <button type="submit" class="btn">
              {% if user in post.like_users.all %}
              <img src="{% static 'images/post_like.png' %}" alt="">
              {% else %}
              <img src="{% static 'images/post_unlike.png' %}" alt="">
              {% endif %}
            </button>
          </form>

      </a>
        <a href="#">
          <img src="{% static 'images/post_comment.png' %}" alt="">
        </a>
      </div>
      <div class="btn-right">
        {% if user == post.author %}
        <a href="{% url 'post:post_modify' post_pk=post.pk %}" class="btn">수정하기</a>
        <a href="{% url 'post:post_delete' post_pk=post.pk %}" class="btn">삭제하기</a>
        {% endif %}
      </div>
    </div>
    <p class="comment">
      {% if post.like_users.exists %}
        {% if post.like_users.count > 10 %}
        <span>좋아요 {{ post.like_users.count }}개</span>
        {% else %}
        <span>{{ post.like_users.all|join:', ' }}</span>님이 좋아합니다.
        {% endif %}
      {% else %}
      <span>처음으로 좋아요를 눌러보세요</span>
      {% endif %}
    </p>
    <div class="post-comment-container">
      <!--해당 post에 my_comment가 있을 경우 표시-->
      {% if post.my_comment %}
        <!--include한 post_comment내에서 'comment'라는 이름으로 쓸 변수에는 post.my_comment를 할당-->
        {% include 'include/post_comment.html' with comment=post.my_comment style='red' %}
      {% endif %}

      <!--post에 연결된 Comment목록을 for문으로 순회하며 아래의 div.post-comment를 반복-->
      {% for comment in post.comment_set.all %}
        {% if comment != post.my_comment %}
          <!--
            include한 post_comment내에서 이미 'comment'라는 이름을 사용중이며
            for문에서 사용하는 각 loop의 아이템 이름 'comment'와 일치
          -->
          {% include 'include/post_comment.html' %}
        {% endif %}
      {% endfor %}
    </div>
    <p class="created">{{ post.created_date }}</p>
    <form action="{% url 'post:comment_create' post_pk=post.pk %}?next={{ request.path }}{{ request.GET|query_string }}#post-{{ post.pk }}" method="POST">
      <!--next주소의 page Get parameter를 수동으로 지정할 때-->
      <!--<form action="{% url 'post:comment_create' post_pk=post.pk %}?next={{ request.path }}?page={{ request.GET.page }}#post-{{ post.pk }}" method="POST">-->
      {% csrf_token %}
      {{ comment_form.content }}
    </form>
  </div>
</article>

django_app/templates/include/post_comment.html
<div class="post-comment" {% if style == 'red' %}style="color: red;"{% endif %}>
  <a href="" class="comment-author">{{ comment.author }}</a>
  <p class="comment-content">{{ comment.html_content|safe }}</p>
  {% if request.user == comment.author %}
  <a href="{% url 'post:comment_modify' comment_pk=comment.pk %}?next={{ request.path }}#post-{{ comment.post.pk }}" class="btn btn-xs">수정</a>
  <form action="{% url 'post:comment_delete' comment_pk=comment.pk %}?next={{ request.path }}#post-{{ comment.post.pk }}" method="POST" class="form-inline">
    {% csrf_token %}
    <button type="submit" class="btn btn-xs">삭제</button>
  </form>
  {% endif %}
</div>